version: "3.8"

services:
  postgres:
    container_name: cerc-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cerc
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cerc
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
